### ISSUE TITLE
How instance two gallery or carousel??

### ISSUE THREAD

**Issue by ghost** [2amigos/yii2-gallery-widget#11]
Hello all
is it possible to instance two widget of 2amigos Gallery || Carousel on the same views page?? For example: i have a page with a Carousel that work fine, without problem. On the same page i insert also another control Gallery with the same instance:

<?= dosamigos\gallery\Carousel::widget(['items' => $items]);?>  
.. .. ..
<?= dosamigos\gallery\Gallery::widget(['items' => $items]);?>

When select an image of my Gallery, 2amigos don't show the previous resource gallery images.

Thanks
Marco

**Comment by tonydspaniard** [comment]
see here: https://github.com/2amigos/yii2-gallery-widget/issues/1#issuecomment-101305385

**Comment by ghost** [comment]
thanks!
