### ISSUE TITLE
ERROR ON COMPOSER INSTALLATION.

### ISSUE THREAD

**Issue by osnwach** [2amigos/yii2-gallery-widget#15]
Please how can I install this with Composer.

I tried: require "2amigos/yii2-gallery-widget" "~1.0"

It gave me an error: 'Your requirement could not be resolved to an installable set of packages'

The package is not available in a stable-enough version according to your minimum stability setting.

Please What can I do to install it ?

**Comment by Federico39** [comment]
Sorry, cannot help. Also tried it and received similar response, will now
cancel interest.

Am still looking for a stable responsive (jquery) photo gallery. Any help
appreciated, have gone through all 20jquery could not decide yet.

2016-04-04 15:51 GMT+02:00 osnwach notifications@github.com:

**Comment by osnwach** [comment]
@Federico39  Thanks for concern

But when I tried:  require "2amigos/yii2-gallery-widget" " \* "

Composer responded fine, but it deleted some packages I have previously installed !

How can we contact Tony (the developer) to help us resolve the issue ?

ALSO  When you pick a good (JQuery) photo gallery, kindly let me know.

Thanks.

**Comment by tonydspaniard** [comment]
@osnwach I have reviewed and its working on my end... not sure how the gallery would delete packages previously installed if you simply require gallery. Yii2 had some issues and I didn't update... trying to fix now. 

By the way, this jquery photo gallery is simply amazing: https://cdnjs.com/libraries/lightgallery

**Comment by ghost** [comment]
No problems. Required with composer without a hiccup, cut and pasted demo code into a view, all  ran perfectly. Nice work.

Curiously, composer did not report it uninstalled:

```
$ composer remove 2amigos/yii2-gallery-widget:~1.0
2amigos/yii2-gallery-widget:~1.0 is not required in your composer.json and has not been removed
Package "2amigos/yii2-gallery-widget:~1.0" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Indeed. It is still listed as a requirement in composer.json.
Well what do I know. Composer scares me.
Happily, the old fashioned "back it all up first" approach still works ;)
