### ISSUE TITLE
bower-asset/blueimp-gallery could not be found in any version

### ISSUE THREAD

**Issue by bryan1996akl** [2amigos/yii2-gallery-widget#21]
Can't figure out how to install yii2-gallery-widget. I've tried many things. Any hints appreciated. Here are the error messages from composer:

 - 2amigos/yii2-gallery-widget 1.0.3 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.2 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.1 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.0 requires bower-asset/blueimp-gallery ~2.15 -> no matching package found.
    - Installation request for 2amigos/yii2-gallery-widget ^1.0 -> satisfiable by 2amigos/yii2-gallery-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3].

 - The requested package bower-asset/blueimp-gallery could not be found in any version, there may be a typo in the package name.

**Comment by tonydspaniard** [comment]
Can you try adding this to your composer.json file?

```
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by bryan1996akl** [comment]
I modified my composer.json per your suggestion. Still not getting bower-asset/blueimp-gallery to install. It seems like composer can't find any versions of blueimp-gallery. Basically seeing same error messages from composer:

    - 2amigos/yii2-gallery-widget 1.0.x-dev requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.1.0 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.3 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.2 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.1 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.0 requires bower-asset/blueimp-gallery ~2.15 -> no matching package found.
    - Installation request for 2amigos/yii2-gallery-widget ~1.0 -> satisfiable by 2amigos/yii2-gallery-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.0.x-dev].

Could not find package bower-asset/blueimp-gallery at any version for your
  minimum-stability (dev). Check the package spelling or your minimum-stabili
  ty

**Comment by bryan1996akl** [comment]
I'm trying from my production server, which isn't recommended. But, composer has worked for all other package installs from my production server. I'm going to try from my local development server.

**Comment by bryan1996akl** [comment]
When moving project to production server I did not run command: composer global require "fxp/composer-asset-plugin:^1.3.1"
After running this command on production the install worked.
