### ISSUE TITLE
issue installing the gallery widget

### ISSUE THREAD

**Issue by chrisjnr** [2amigos/yii2-gallery-widget#23]
Good day,
I keep getting this error whenever i try to install the widget.
I have changed my minimum stability setting in my composer.json to @dev, but still I keep getting the same error
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-gallery-widget 1.0.x-dev requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.1.0 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.3 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.2 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.1 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.0 requires bower-asset/blueimp-gallery ~2.15 -> no matching package found.
    - Installation request for 2amigos/yii2-gallery-widget ~1.0 -> satisfiable by 2amigos/yii2-gallery-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by tonydspaniard** [comment]
Please add: 

```json 
"minimum-stability": "dev",
"prefer-stable": true,
```

to your composer file.

**Comment by chrisjnr** [comment]
thanks for your swift reply,
i already did that but it still gives me the same error
this is what my composer.json looks like

```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "kartik-v/yii2-widget-datepicker": "@dev",
        "yidas/yii2-bower-asset": "^2.0",
        "kartik-v/yii2-grid": "@dev",
        "kartik-v/yii2-editable": "@dev",
        "perminder-klair/yii2-dropzone": "dev-master",
        "mpdf/mpdf": "@dev",
        "slavkovrn/yii2-imagegalary": "*",
        "2amigos/yii2-google-maps-library": "*",
        "kartik-v/yii2-widget-activeform": "@dev",
        "dektrium/yii2-user": "^0.9.12",
        "thyseus/yii2-message": "^0.3.0",
        "wolfguard/yii2-gallery": "*",
        "apolle/yii2-gallery-manager": "dev-master",
        "kartik-v/yii2-field-range": "*",
        "noam148/yii2-image-manager": "*",
        "2amigos/yii2-gallery-widget": "~1.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },

    "config": {
        "process-timeout": 1800,
        "fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }
        }
    }
}
```

i still get the same error

**Comment by tonydspaniard** [comment]
what about if you do: `2amigos/yii2-gallery-widget": "1.1.*"`

**Comment by chrisjnr** [comment]
seems to work now. Thanks much appreciated
