### ISSUE TITLE
Gallery not work in other language

### ISSUE THREAD

**Issue by KaungZawHtet** [2amigos/yii2-gallery-widget#27]
I m trying to use this gallery widget:  https://github.com/2amigos/yii2-gallery-widget
Everything is fine and images are detected when url is in default language (i.e: www.myapp.com/index.php/uploads/myimg.jpg )
This widget not work and display only images without gallery widget when url is in other language i.e ( www.myapp.com/index.php/cn/uploads/myimg.jpg )
I configure like this : ‘src’ => Url::to(’@web/uploads/myimage.jpg) and this only work in default language. What’s the problem with it ?

**Comment by tonydspaniard** [comment]
@KaungZawHtet the URLs do not look properly configured. Are you sure are `/uploads` and `/cn/uploads` and not `/uploads/cn`? The problem has nothing to do with the widget but to the images location.
