### ISSUE TITLE
Change size gallery

### ISSUE THREAD

**Issue by 20tech** [2amigos/yii2-gallery-widget#4]
Hi Dear, and tank you for this Extension useful,

I have a question : How Can I Change Width and height Gallery slide show? 
I have a div with width:600px and height : 400px; I put the code in there, but it is much larger than 600x400 :(.

Plz guide me !!

**Comment by fastangel** [comment]
In .blueimp-gallery.min.css change .blueimp-gallery-carousel{.... padding-bottom

**Comment by tonydspaniard** [comment]
About to refactor the library to be part of http://yiiwheels.com sorry if i take time to respond as to refactor all our extensions is quite a lot of work

**Comment by tonydspaniard** [comment]
I think your question can be answered here: https://github.com/blueimp/Gallery#container-and-element-options
