### ISSUE TITLE
Uncaught ReferenceError: blueimp is not defined

### ISSUE THREAD

**Issue by hdushku** [2amigos/yii2-gallery-widget#6]
I get this error in console:

GET http://localhost/webapplication/frontend/web/assets/5aaa8e05/css/blueimp-gallery.min.css 
1:462 GET http://localhost/webapplication/frontend/web/assets/5aaa8e05/js/blueimp-gallery.min.js 404 (Not Found)
1:468 Uncaught ReferenceError: blueimp is not defined

**Comment by tonydspaniard** [comment]
@creocoder will handle it.

**Comment by tonydspaniard** [comment]
@hdushku make sure the bower plugin was installed properly. Apologies for such delayed answer.
